//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCrudProject.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user_reg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_reg()
        {
            this.UserRoles = new HashSet<UserRole>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string First_Name { get; set; }

        public string Middle_Name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Last_Name { get; set; }

        public Nullable<int> Age { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public System.DateTime DoB { get; set; }

        public string Address { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "This field is required")]
        // [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string Password { get; set; }


        [DisplayName("Upload Image")]
        public byte[] ImageBinary { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
